version: "3.9"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  web:
    build: .
    env_file:
      - .env
    command: bundle exec rails server -b 0.0.0.0
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: myapp_production
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data: