version: 2.1

executors:
  ruby-executor:
    docker:
      - image: cimg/ruby:3.2.2-node
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_DB: $POSTGRES_DB
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    working_directory: ~/app

jobs:
  setup:
    executor: ruby-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Clear old gems & reinstall dependencies
          command: |
            bundle clean --force
            run: bundle clean --force
            rm -rf ~/.bundle
            rm -rf vendor/bundle
            rm -rf Gemfile.lock
            bundle install --jobs=4 --retry=3

      - run:
          name: Check if Rails is installed
          command: bundle list | grep rails

      - save_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  test:
    executor: ruby-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Setup database
          command: |
            bundle exec bin/rails db:create
            bundle exec bin/rails db:schema:load
      - run:
          name: Run RSpec
          command: bundle exec bin/rails rspec

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - setup
      - test:
          requires:
            - setup
