version: 2.1

executors:
  ruby-executor:
    docker:
      - image: cimg/ruby:3.2.2-node
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
      - image: redis:7  # 🚀 Redisをサービスとして追加
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: Kotatsumuri
          POSTGRES_PASSWORD: postgres
    working_directory: ~/app

jobs:
  setup:
    executor: ruby-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Wait for Redis
          command: dockerize -wait tcp://localhost:6379 -timeout 30s

      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3


      - save_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  test:
    executor: ruby-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - gems-{{ checksum "Gemfile.lock" }}

      - run:
          name: Clear old cache
          command: |
            rm -rf Gemfile.lock
            rm -rf ~/.bundle vendor/bundle
            bundle install --path vendor/bundle --jobs=4 --retry=3

      - run:
          name: Setup database
          command: |
            bundle exec bin/rails db:create
            bundle exec bin/rails db:schema:load
      - run:
          name: Run RSpec
          command: bundle exec bin/rails rspec

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - setup
      - test:
          requires:
            - setup
